
const notificationLog =  require('../../src/app/controllers/log/NotificationLogController')
const {log} = require('../../src/app/models/')
const logtype = require('../../src/app/controllers/enum/logType')
describe('Log tests', () => {
    it('Should create notifications without errors', async (done) => {

        await notificationLog.error('Log Test','This error has been generated by log test')
        
        
        setTimeout(() => {}, 3000)

        response = await log.findOne({where:{idLogType:logtype["notification_error_500"].value}})
        expect(response.idLog).toBe(1)
        done()
    })
 
    it('Check if the activity notification has been created', async (done) => {

        await notificationLog.activity('Log Test','This error has been generated by log test')
        
        
        setTimeout(() => {}, 3000)

        response = await log.findOne({where:{idLogType:logtype["notification_activity"].value}})
        expect(response.idLogType).toBe(logtype["notification_activity"].value)
        done()
    })
})